export const estados = [
  {
    nome: "Acre",
    sigla: "AC",
    capital: "Rio Branco",
    populacao: 830000,
    pib: 15300000000,
    atividadesEconomicas: ["Agricultura", "Pecuária", "Serviços públicos"],
    informacoesGeograficas: { areaKm2: 164123.04, bioma: "Amazônia" },
    bandeira: "http://localhost:3000/static/bandeiras/AC.png",
    regiao: "Norte"
  },
  {
    nome: "Alagoas",
    sigla: "AL",
    capital: "Maceió",
    populacao: 3353000,
    pib: 52800000000,
    atividadesEconomicas: ["Agroindústria", "Turismo", "Serviços"],
    informacoesGeograficas: { areaKm2: 27767.7, bioma: "Mata Atlântica" },
    bandeira: "http://localhost:3000/static/bandeiras/AL.png",
    regiao: "Nordeste"
  },
  {
    nome: "Amapá",
    sigla: "AP",
    capital: "Macapá",
    populacao: 877000,
    pib: 15900000000,
    atividadesEconomicas: ["Extrativismo", "Serviços públicos", "Comércio"],
    informacoesGeograficas: { areaKm2: 142828.52, bioma: "Amazônia" },
    bandeira: "http://localhost:3000/static/bandeiras/AP.png",
    regiao: "Norte"
  },
  {
    nome: "Amazonas",
    sigla: "AM",
    capital: "Manaus",
    populacao: 4200000,
    pib: 118000000000,
    atividadesEconomicas: ["Zona Franca", "Comércio", "Turismo"],
    informacoesGeograficas: { areaKm2: 1570745.68, bioma: "Amazônia" },
    bandeira: "http://localhost:3000/static/bandeiras/AM.png",
    regiao: "Norte"
  },
  {
    nome: "Bahia",
    sigla: "BA",
    capital: "Salvador",
    populacao: 14800000,
    pib: 340000000000,
    atividadesEconomicas: ["Turismo", "Petróleo", "Agropecuária"],
    informacoesGeograficas: { areaKm2: 564692.67, bioma: "Caatinga e Mata Atlântica" },
    bandeira: "http://localhost:3000/static/bandeiras/BA.png",
    regiao: "Nordeste"
  },
  {
    nome: "Ceará",
    sigla: "CE",
    capital: "Fortaleza",
    populacao: 9240000,
    pib: 165000000000,
    atividadesEconomicas: ["Indústria", "Turismo", "Comércio"],
    informacoesGeograficas: { areaKm2: 148825.6, bioma: "Caatinga" },
    bandeira: "http://localhost:3000/static/bandeiras/CE.png",
    regiao: "Nordeste"
  },
  {
    nome: "Distrito Federal",
    sigla: "DF",
    capital: "Brasília",
    populacao: 3094000,
    pib: 289000000000,
    atividadesEconomicas: ["Administração pública", "Serviços", "Comércio"],
    informacoesGeograficas: { areaKm2: 5779.99, bioma: "Cerrado" },
    bandeira: "http://localhost:3000/static/bandeiras/DF.png",
    regiao: "Centro-Oeste"
  },
  {
    nome: "Espírito Santo",
    sigla: "ES",
    capital: "Vitória",
    populacao: 4064000,
    pib: 160000000000,
    atividadesEconomicas: ["Mineração", "Exportação portuária", "Agronegócio"],
    informacoesGeograficas: { areaKm2: 46077.5, bioma: "Mata Atlântica" },
    bandeira: "http://localhost:3000/static/bandeiras/ES.png",
    regiao: "Sudeste"
  },
  {
    nome: "Goiás",
    sigla: "GO",
    capital: "Goiânia",
    populacao: 7245000,
    pib: 272000000000,
    atividadesEconomicas: ["Agronegócio", "Mineração", "Indústria"],
    informacoesGeograficas: { areaKm2: 340111.78, bioma: "Cerrado" },
    bandeira: "http://localhost:3000/static/bandeiras/GO.png",
    regiao: "Centro-Oeste"
  },
  {
    nome: "Maranhão",
    sigla: "MA",
    capital: "São Luís",
    populacao: 7100000,
    pib: 98000000000,
    atividadesEconomicas: ["Agropecuária", "Portuária", "Indústria"],
    informacoesGeograficas: { areaKm2: 331937.45, bioma: "Amazônia e Cerrado" },
    bandeira: "http://localhost:3000/static/bandeiras/MA.png",
    regiao: "Nordeste"
  },
  {
    nome: "Mato Grosso",
    sigla: "MT",
    capital: "Cuiabá",
    populacao: 3600000,
    pib: 230000000000,
    atividadesEconomicas: ["Agronegócio", "Comércio", "Serviços"],
    informacoesGeograficas: { areaKm2: 903357.91, bioma: "Cerrado e Amazônia" },
    bandeira: "http://localhost:3000/static/bandeiras/MT.png",
    regiao: "Centro-Oeste"
  },
  {
    nome: "Mato Grosso do Sul",
    sigla: "MS",
    capital: "Campo Grande",
    populacao: 2800000,
    pib: 150000000000,
    atividadesEconomicas: ["Agropecuária", "Indústria", "Serviços"],
    informacoesGeograficas: { areaKm2: 357125.0, bioma: "Cerrado e Pantanal" },
    bandeira: "http://localhost:3000/static/bandeiras/MS.png",
    regiao: "Centro-Oeste"
  },
  {
    nome: "Minas Gerais",
    sigla: "MG",
    capital: "Belo Horizonte",
    populacao: 21100000,
    pib: 820000000000,
    atividadesEconomicas: ["Mineração", "Indústria", "Agronegócio"],
    informacoesGeograficas: { areaKm2: 586528.29, bioma: "Cerrado e Mata Atlântica" },
    bandeira: "http://localhost:3000/static/bandeiras/MG.png",
    regiao: "Sudeste"
  },
  {
    nome: "Pará",
    sigla: "PA",
    capital: "Belém",
    populacao: 8700000,
    pib: 180000000000,
    atividadesEconomicas: ["Mineração", "Energia", "Agricultura"],
    informacoesGeograficas: { areaKm2: 1247954.66, bioma: "Amazônia" },
    bandeira: "http://localhost:3000/static/bandeiras/PA.png",
    regiao: "Norte"
  },
  {
    nome: "Paraíba",
    sigla: "PB",
    capital: "João Pessoa",
    populacao: 4030000,
    pib: 67000000000,
    atividadesEconomicas: ["Serviços", "Comércio", "Turismo"],
    informacoesGeograficas: { areaKm2: 56584.6, bioma: "Caatinga" },
    bandeira: "http://localhost:3000/static/bandeiras/PB.png",
    regiao: "Nordeste"
  },
  {
    nome: "Paraná",
    sigla: "PR",
    capital: "Curitiba",
    populacao: 11400000,
    pib: 550000000000,
    atividadesEconomicas: ["Indústria", "Agronegócio", "Tecnologia"],
    informacoesGeograficas: { areaKm2: 199307.9, bioma: "Mata Atlântica" },
    bandeira: "http://localhost:3000/static/bandeiras/PR.png",
    regiao: "Sul"
  },
  {
    nome: "Pernambuco",
    sigla: "PE",
    capital: "Recife",
    populacao: 9610000,
    pib: 210000000000,
    atividadesEconomicas: ["Comércio", "Serviços", "Indústria"],
    informacoesGeograficas: { areaKm2: 98311.6, bioma: "Caatinga e Mata Atlântica" },
    bandeira: "http://localhost:3000/static/bandeiras/PE.png",
    regiao: "Nordeste"
  },
  {
    nome: "Piauí",
    sigla: "PI",
    capital: "Teresina",
    populacao: 3280000,
    pib: 52000000000,
    atividadesEconomicas: ["Agricultura", "Serviços", "Comércio"],
    informacoesGeograficas: { areaKm2: 251529.2, bioma: "Caatinga e Cerrado" },
    bandeira: "http://localhost:3000/static/bandeiras/PI.png",
    regiao: "Nordeste"
  },
  {
    nome: "Rio de Janeiro",
    sigla: "RJ",
    capital: "Rio de Janeiro",
    populacao: 17300000,
    pib: 830000000000,
    atividadesEconomicas: ["Petróleo", "Turismo", "Serviços"],
    informacoesGeograficas: { areaKm2: 43796.1, bioma: "Mata Atlântica" },
    bandeira: "http://localhost:3000/static/bandeiras/RJ.png",
    regiao: "Sudeste"
  },
  {
    nome: "Rio Grande do Norte",
    sigla: "RN",
    capital: "Natal",
    populacao: 3530000,
    pib: 66000000000,
    atividadesEconomicas: ["Turismo", "Petróleo", "Agricultura"],
    informacoesGeograficas: { areaKm2: 52811.1, bioma: "Caatinga" },
    bandeira: "http://localhost:3000/static/bandeiras/RN.png",
    regiao: "Nordeste"
  },
  {
    nome: "Rio Grande do Sul",
    sigla: "RS",
    capital: "Porto Alegre",
    populacao: 11300000,
    pib: 590000000000,
    atividadesEconomicas: ["Agricultura", "Pecuária", "Indústria"],
    informacoesGeograficas: { areaKm2: 281748.5, bioma: "Pampa e Mata Atlântica" },
    bandeira: "http://localhost:3000/static/bandeiras/RS.png",
    regiao: "Sul"
  },
  {
    nome: "Rondônia",
    sigla: "RO",
    capital: "Porto Velho",
    populacao: 1800000,
    pib: 53000000000,
    atividadesEconomicas: ["Pecuária", "Agricultura", "Energia"],
    informacoesGeograficas: { areaKm2: 237576.2, bioma: "Amazônia" },
    bandeira: "http://localhost:3000/static/bandeiras/RO.png",
    regiao: "Norte"
  },
  {
    nome: "Roraima",
    sigla: "RR",
    capital: "Boa Vista",
    populacao: 650000,
    pib: 15000000000,
    atividadesEconomicas: ["Comércio", "Serviços", "Agricultura"],
    informacoesGeograficas: { areaKm2: 224300.5, bioma: "Amazônia" },
    bandeira: "http://localhost:3000/static/bandeiras/RR.png",
    regiao: "Norte"
  },
  {
    nome: "Santa Catarina",
    sigla: "SC",
    capital: "Florianópolis",
    populacao: 7700000,
    pib: 430000000000,
    atividadesEconomicas: ["Indústria", "Tecnologia", "Turismo"],
    informacoesGeograficas: { areaKm2: 95736.2, bioma: "Mata Atlântica" },
    bandeira: "http://localhost:3000/static/bandeiras/SC.png",
    regiao: "Sul"
  },
  {
    nome: "São Paulo",
    sigla: "SP",
    capital: "São Paulo",
    populacao: 46600000,
    pib: 2700000000000,
    atividadesEconomicas: ["Indústria", "Serviços", "Tecnologia"],
    informacoesGeograficas: { areaKm2: 248209.4, bioma: "Mata Atlântica" },
    bandeira: "http://localhost:3000/static/bandeiras/SP.png",
    regiao: "Sudeste"
  },
  {
    nome: "Sergipe",
    sigla: "SE",
    capital: "Aracaju",
    populacao: 2320000,
    pib: 47000000000,
    atividadesEconomicas: ["Petróleo", "Turismo", "Agropecuária"],
    informacoesGeograficas: { areaKm2: 21910.4, bioma: "Caatinga" },
    bandeira: "http://localhost:3000/static/bandeiras/SE.png",
    regiao: "Nordeste"
  },
  {
    nome: "Tocantins",
    sigla: "TO",
    capital: "Palmas",
    populacao: 1600000,
    pib: 46000000000,
    atividadesEconomicas: ["Agropecuária", "Energia", "Comércio"],
    informacoesGeograficas: { areaKm2: 277620.9, bioma: "Cerrado e Amazônia" },
    bandeira: "http://localhost:3000/static/bandeiras/TO.png",
    regiao: "Norte"
  }
];
